spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ust_calculator
    username: ust_user
    password: ust_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    br.gov.ust.calculator: DEBUG
    org.springframework.security: INFO
